version: '3'
services:
  app:
    build: .
    image: stravinest/fungap

  production:
    image: ${DOCKER_USER_ID}/fungap:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - '3000:3000'
    command: node app.js

